### ISSUE TITLE
[Questions] About the Edge Box Proposals Extraction

### ISSUE THREAD

**Issue by wuyujack** [manoja328/rodeo#3]
Hi Manoj,

Thank you for your great work! I notice that the `README` only provides the Edgebox proposals file for the VOC 2007, and I also check the file `extract_coco_features.py` that there do not include any EdgeBox proposals for the MSCOCO 2014. 

This makes me confused because based on your paper, you mentioned that you are using the edge box proposals following the ILWFOD [CVPR 2017] in **Section 5.5 Implementation Details**. Do I misunderstand this detail? Is there any reason for the missing edge box proposals for the MSCOCO 2014 dataset?

The other question is: how can I obtain the edge box, e.g. your provided edge box proposals file for VOC 2007?

Best,
Mingfu

**Comment by wuyujack** [comment]
Hi Manoj,

I check the file `extract_coco_features.py`, and it seems you are using the pretrained model `iter0_models_incr_coco/chkpt9.pth` to extract the feature directly, shown in https://github.com/manoja328/rodeo/blob/72b2a1915d80062ecd7c8e20636065c820805115/extract_coco_features.py#L46-L60 This seems to be not including the edge box for the MSCOCO.
 
May I know if it is still available to get this pretrained model to reproduce the MSCOCO feature for training? If not, how can we generate this pretrained model by ourselves? I really appreciate any help you can provide. Your advice would be precious. 

BTW, have you reproduced the ICCV 2017 paper "Incremental Learning of Object Detectors without Catastrophic Forgetting"? Just curious since it seems hard to run their MSCOCO experiments.

Regards,
Mingfu

**Comment by manoja328** [comment]
Hi, in the google drive link given in the readme i have uploaded the checkpionts file and also the edgeboxes proposals for both MSCOCO and VOC. Hope that will help you. Also, I was unable to reproduce the ICCV 2017 paper.

**Comment by wuyujack** [comment]
Thank you so much for your help! I am so grateful for your assistance.
